'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, LocateFixed, MapPin, Save, Sparkles } from 'lucide-react';

export default function DesignerOnboarding(){
 const router=useRouter();const [salonName,setSalonName]=useState('');const [address,setAddress]=useState('');const [bio,setBio]=useState('');const [years,setYears]=useState(3);const [radius,setRadius]=useState(5);const [instagram,setInstagram]=useState('');const [specialties,setSpecialties]=useState<string[]>(['剪髮']);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [lat,setLat]=useState<number|null>(null);const [lng,setLng]=useState<number|null>(null);const [geo,setGeo]=useState('');
 const all=['洗髮','剪髮','染髮','燙髮','護髮','造型'];const toggle=(x:string)=>setSpecialties(s=>s.includes(x)?s.filter(v=>v!==x):[...s,x]);
 useEffect(()=>{fetch('/api/designer/profile').then(r=>r.ok?r.json():null).then(j=>{const p=j?.profile;if(!p)return;setSalonName(p.salon_name||'');setAddress(p.address||'');setBio(p.bio||'');setYears(Number(p.years_experience||0));setRadius(Number(p.service_radius_km||5));setInstagram(p.instagram||'');setSpecialties(p.specialties?.length?p.specialties:['剪髮']);setLat(p.lat??null);setLng(p.lng??null);if(p.lat&&p.lng)setGeo('已儲存店家定位')}).catch(()=>{})},[]);
 function useGeo(){if(!navigator.geolocation){setGeo('此瀏覽器不支援定位');return}setGeo('定位中…');navigator.geolocation.getCurrentPosition(p=>{setLat(p.coords.latitude);setLng(p.coords.longitude);setGeo(`定位完成 · 精準度約 ${Math.round(p.coords.accuracy)}m`)},()=>setGeo('定位失敗，請確認 iPhone / Android 瀏覽器定位權限'),{enableHighAccuracy:true,timeout:10000,maximumAge:120000})}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/designer/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({salonName,address,bio,yearsExperience:years,specialties,radiusKm:radius,isAcceptingNow:true,instagram,lat,lng})});const j=await r.json();if(!r.ok) throw new Error(j.message||'儲存失敗');router.push('/pro/profile');router.refresh()}catch(err:any){setError(err.message)}finally{setBusy(false)}}
 return <div className="app-shell"><div className="topbar"><div className="container"><Link className="brand" href="/"><span className="brand-mark"><ArrowLeft size={16}/></span>設計師加入設定</Link></div></div><main className="container page"><div className="layout-2"><section><div className="eyebrow">DESIGNER ONBOARDING</div><h1 className="page-title">讓附近顧客知道，<br/>你現在可以接。</h1><p className="muted">店家定位會用來做真實距離排序。iPhone Safari 與 Android Chrome 都會用同一套 GPS 流程。</p><div className="panel"><form onSubmit={submit}><div className="form-grid"><div className="form-group"><label>髮廊／工作室名稱</label><input className="input" required value={salonName} onChange={e=>setSalonName(e.target.value)} placeholder="例如：EQUAL HAIR"/></div><div className="form-group"><label><MapPin size={13}/>服務地址</label><input className="input" required value={address} onChange={e=>setAddress(e.target.value)} placeholder="竹北市科大二街…"/><button className="btn btn-soft" type="button" style={{marginTop:8}} onClick={useGeo}><LocateFixed size={14}/>使用店家目前定位</button><span className="small" style={{marginLeft:8}}>{geo}</span></div></div><div className="form-grid"><div className="form-group"><label>從業年資</label><input className="input" type="number" min="0" max="80" value={years} onChange={e=>setYears(Number(e.target.value))}/></div><div className="form-group"><label>接案半徑（公里）</label><input className="input" type="number" min="0.5" max="50" step="0.5" value={radius} onChange={e=>setRadius(Number(e.target.value))}/></div></div><div className="form-group"><label>擅長項目</label><div className="service-grid">{all.map(x=><button type="button" key={x} className={`service-chip ${specialties.includes(x)?'active':''}`} onClick={()=>toggle(x)}>{x}</button>)}</div></div><div className="form-group"><label>自我介紹</label><textarea className="input textarea" value={bio} onChange={e=>setBio(e.target.value)} placeholder="擅長風格、溝通方式、你的專業特色…"/></div><div className="form-group"><label>Instagram（選填）</label><input className="input" value={instagram} onChange={e=>setInstagram(e.target.value)} placeholder="@your_account"/></div>{error&&<div className="form-error">{error}</div>}<button className="btn btn-primary" type="submit" style={{width:'100%',padding:15}} disabled={busy}><Save size={16}/>{busy?'儲存中…':'儲存並設定作品與價目'}</button></form></div></section><aside className="panel summary-box"><Sparkles size={26} color="#527d58"/><h3>完成後會立即開啟</h3><div className="summary-row"><span>附近需求牆</span><strong>✓</strong></div><div className="summary-row"><span>GPS 真距離</span><strong>{lat&&lng?'✓':'待定位'}</strong></div><div className="summary-row"><span>接案半徑</span><strong>{radius} km</strong></div><div className="summary-row"><span>iOS / Android</span><strong>雙平台</strong></div></aside></div></main></div>
}
