import { Header, MobileNav } from '@/components/Header';
import { providers } from '@/lib/demo-data';
import { hasDatabase, query } from '@/lib/server-db';
import type { Provider } from '@/lib/types';
export default async function ProviderPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;let p:Provider=providers.find(x=>x.id===id)||providers[0];
 if(hasDatabase()){try{const r=await query(`select u.id,u.display_name,u.avatar_url,coalesce(s.name,'獨立設計師') salon,coalesce(s.address,'') location,coalesce(s.cover_url,'') cover,coalesce(s.instagram,'') instagram,coalesce(dp.avg_rating,0) rating,coalesce(dp.review_count,0) reviews,coalesce(dp.completed_count,0) completed,dp.is_accepting_now,dp.specialties,coalesce(dp.bio,'') bio from users u join designer_profiles dp on dp.user_id=u.id left join salons s on s.id=dp.salon_id where u.id=$1 limit 1`,[id]);if(r.rows[0]){const x:any=r.rows[0];const works=await query(`select image_url from portfolio_items where designer_user_id=$1 order by sort_order,created_at desc limit 24`,[id]);const services=await query(`select label,price_from,price_to from service_items where designer_user_id=$1 and is_active=true order by created_at`,[id]);p={id:x.id,name:x.display_name,salon:x.salon,avatar:x.avatar_url||p.avatar,cover:x.cover||p.cover,rating:Number(x.rating||0),reviews:x.reviews||0,completed:x.completed||0,distanceKm:null,availableText:x.is_accepting_now?'現在可接':'可詢問時段',isAvailableNow:Boolean(x.is_accepting_now),location:x.location,specialties:x.specialties||[],intro:x.bio,instagram:x.instagram,works:works.rows.map((w:any)=>w.image_url),services:services.rows.map((s:any)=>({label:s.label,price:s.price_to?`NT$ ${s.price_from} - ${s.price_to}`:`NT$ ${s.price_from||0} 起`}))}}}catch{}}
 return <div className="app-shell"><Header/><main className="container page"><div className="profile-hero"><img src={p.cover}/><div className="profile-overlay"><div className="provider-row"><img className="avatar" src={p.avatar}/><div><h1 style={{margin:0}}>{p.name}｜{p.salon}</h1><div>★ {p.rating}（{p.reviews}） · 完成 {p.completed} 次</div></div></div></div></div><div className="profile-main"><div><div className="panel"><h3>關於我</h3><p className="muted" style={{lineHeight:1.8}}>{p.intro||'設計師尚未填寫自我介紹。'}</p><div className="tags">{p.specialties.map(x=><span className="tag" key={x}>{x}</span>)}</div></div><div className="panel" style={{marginTop:16}}><h3>作品集</h3>{p.works.length?<div className="work-grid">{p.works.map(x=><img src={x} key={x}/>)}</div>:<p className="small">作品集尚未上傳。</p>}</div></div><aside><div className="panel summary-box"><div className="status-pill" style={{position:'static',display:'inline-block'}}>{p.isAvailableNow?'現在可接':'可詢問時段'}</div><h2 style={{marginBottom:4}}>{p.availableText}</h2><p className="small">{p.location}</p><a className="btn btn-primary" style={{width:'100%',margin:'10px 0',display:'block',textAlign:'center'}} href="/request/new">發布需求邀請報價</a><button className="btn" style={{width:'100%'}} disabled>收到報價後可聊天</button><h3 style={{marginTop:22}}>服務價格</h3>{p.services.length?p.services.map(s=><div className="summary-row" key={s.label}><span>{s.label}</span><strong>{s.price}</strong></div>):<p className="small">尚未建立公開價目表。</p>}<div className="summary-row"><span>Instagram</span><strong>{p.instagram||'未設定'}</strong></div></div></aside></div></main><MobileNav/></div>
}
