import Link from 'next/link';
import { Clock3, Eye, HeartPulse, LocateFixed, MapPin, Scissors, Sparkles, WandSparkles } from 'lucide-react';
import { Header, MobileNav } from '@/components/Header';
import { ProviderCard } from '@/components/ProviderCard';
import { BRAND } from '@/lib/brand';
import { hasDatabase, query } from '@/lib/server-db';
import { SERVICE_CATALOG } from '@/lib/service-catalog';
import type { Provider } from '@/lib/types';

const iconMap:any={hair:Scissors,nails:Sparkles,lashes:Eye,beauty:HeartPulse};
function mapProvider(x:any):Provider{return {id:x.id,name:x.display_name,salon:x.organization_name||'個人工作者',organization:x.organization_name,avatar:x.avatar_url||'/icons/icon-192.png',cover:x.cover||'/icons/icon-512.png',rating:Number(x.rating||0),reviews:Number(x.reviews||0),completed:Number(x.completed||0),distanceKm:null,availableText:x.is_accepting_now?'現在可接':'可詢問時段',isAvailableNow:Boolean(x.is_accepting_now),location:x.location||'',specialties:x.specialties||[],categoryKeys:x.category_keys||[],categoryLabels:x.category_labels||[],intro:x.bio||'',instagram:x.instagram||'',works:[],services:[]}}

export default async function Home(){
 let providers:Provider[]=[];let liveCount=0;let dataError='';let activeKeys=SERVICE_CATALOG.map(c=>c.key);
 if(!hasDatabase())dataError='雲端資料庫尚未連線。';
 else try{
  const [providerRows,countRows,categoryRows]=await Promise.all([
   query(`select u.id,u.display_name,u.avatar_url,coalesce(o.name,'個人工作者') organization_name,coalesce(o.address,'') location,coalesce(o.cover_url,'') cover,coalesce(o.instagram,'') instagram,coalesce(dp.avg_rating,0) rating,coalesce(dp.review_count,0) reviews,coalesce(dp.completed_count,0) completed,dp.is_accepting_now,dp.specialties,coalesce(dp.bio,'') bio,coalesce(array_agg(distinct sc.key) filter(where sc.key is not null and sc.is_active=true),'{}') category_keys,coalesce(array_agg(distinct sc.label) filter(where sc.label is not null and sc.is_active=true),'{}') category_labels from users u join designer_profiles dp on dp.user_id=u.id left join organizations o on o.id=dp.organization_id left join provider_categories pc on pc.user_id=u.id left join service_categories sc on sc.id=pc.category_id where u.role in ('designer','salon_owner') and dp.onboarding_completed=true and dp.approval_status='approved' and u.account_status='active' and exists(select 1 from provider_categories pca join service_categories sca on sca.id=pca.category_id where pca.user_id=u.id and sca.is_active=true) and exists(select 1 from subscriptions sx where ((sx.user_id=u.id) or (dp.organization_id is not null and sx.organization_id=dp.organization_id)) and (sx.comped_forever=true or sx.free_until>now() or sx.status in ('trial','active'))) group by u.id,o.name,o.address,o.cover_url,o.instagram,dp.avg_rating,dp.review_count,dp.completed_count,dp.is_accepting_now,dp.specialties,dp.bio order by dp.is_accepting_now desc,dp.avg_rating desc limit 6`),
   query(`select count(*)::int live from users u join designer_profiles dp on dp.user_id=u.id where u.role in ('designer','salon_owner') and u.account_status='active' and dp.onboarding_completed=true and dp.approval_status='approved' and dp.is_accepting_now=true and exists(select 1 from provider_categories pc join service_categories sc on sc.id=pc.category_id where pc.user_id=u.id and sc.is_active=true) and exists(select 1 from subscriptions sx where ((sx.user_id=u.id) or (dp.organization_id is not null and sx.organization_id=dp.organization_id)) and (sx.comped_forever=true or sx.free_until>now() or sx.status in ('trial','active')))`),
   query(`select key from service_categories where is_active=true order by sort_order`)
  ]);
  providers=providerRows.rows.map(mapProvider);liveCount=Number(countRows.rows[0]?.live||0);activeKeys=categoryRows.rows.map((x:any)=>x.key);
 }catch(e){console.error(e);dataError='服務者資料暫時無法讀取，請確認 R0.6 migration 已完成。'}
 const activeCatalog=SERVICE_CATALOG.filter(c=>activeKeys.includes(c.key));
 return <div className="app-shell"><Header/><main><section className="container hero"><div><div className="eyebrow">BEAUTY ON DEMAND</div><h1>今天想做什麼？<br/>附近的美業專家來找你。</h1><p>{BRAND.description}</p><div className="beauty-category-grid">{activeCatalog.map(c=>{const Icon=iconMap[c.key];return <Link className="beauty-category-card" href={`/discover?category=${c.key}`} key={c.key}><span className="beauty-category-icon"><Icon size={22}/></span><strong>{c.label}</strong><small>{c.description}</small></Link>})}</div><div className="quick-card"><div className="quick-grid"><div className="field"><label><Sparkles size={12}/>服務大類</label><select defaultValue={activeCatalog[0]?.label||''}>{activeCatalog.map(c=><option key={c.key}>{c.label}</option>)}</select></div><div className="field"><label><Clock3 size={12}/>希望時間</label><select defaultValue="現在 / 越快越好"><option>現在 / 越快越好</option><option>今天</option><option>指定日期</option></select></div><div className="field"><label><MapPin size={12}/>地點</label><input defaultValue="竹北市 · 使用目前位置"/></div><Link className="btn btn-primary" style={{display:'grid',placeItems:'center',paddingInline:22}} href="/request/new"><Sparkles size={16}/>發布需求</Link></div></div><div className="small home-proof"><span>✓ 顧客永久免費</span><span>✓ iPhone / Android</span><span>✓ 多美業類別共用媒合</span></div></div><div className="hero-photo"><img src="https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=85" alt="beauty studio"/><div className="hero-float"><div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'center'}}><div><div className="small">目前平台</div><strong style={{fontSize:18}}>{liveCount} 位專業服務者現在可接</strong><div className="small" style={{marginTop:5}}>只顯示已完成資料、通過審核且有使用權限的真實帳號</div></div><span className="brand-mark" style={{width:46,height:46,borderRadius:17}}><LocateFixed size={20}/></span></div></div></div></section>
 <section className="container section"><div className="section-head"><div><div className="eyebrow">NEARBY NOW</div><h2>現在附近有空</h2><p className="muted">依服務類別、定位與可接狀態媒合真實服務者。</p></div><Link className="btn" href="/discover">查看全部</Link></div>{providers.length>0&&<div className="cards">{providers.map(p=><ProviderCard p={p} key={p.id}/>)}</div>}{providers.length===0&&!dataError&&<div className="empty-state"><h3>第一批美業服務者招募中</h3><p className="muted">美髮、美甲、美睫、美容美體都可以加入；通過審核後就會出現在這裡。</p><Link className="btn btn-brand" href="/auth?role=designer">我是服務者／店家</Link></div>}{providers.length===0&&dataError&&<div className="empty-state"><h3>目前沒有顯示服務者資料</h3><p className="muted">{dataError}</p><Link className="btn" href="/api/health">檢查系統連線</Link></div>}</section>
 <section className="container section"><div className="panel"><div className="section-head"><div><div className="eyebrow">HOW IT WORKS</div><h2>選服務、發需求、收提案。</h2></div><WandSparkles size={28} color="#527d58"/></div><div className="cards">{[['01','選擇服務','先選美髮、美甲、美睫或美容美體，再選具體項目。'],['02','收到提案','附近符合類別與距離的服務者回覆時間、價格與作品。'],['03','聊天成交','比較作品、距離與方案，先聊清楚再成立預約。']].map(x=><div className="metric" key={x[0]}><div className="eyebrow">{x[0]}</div><strong style={{fontSize:21}}>{x[1]}</strong><p className="muted" style={{marginBottom:0}}>{x[2]}</p></div>)}</div></div></section></main><footer className="footer"><div className="container">{BRAND.name} · Customer Free · Provider Subscription · iOS / Android Web / PWA</div></footer><MobileNav/></div>
}
