'use client';
import { useState } from 'react';
import { CheckCircle2, RotateCcw, XCircle } from 'lucide-react';
type Item={id:string;display_name:string;email:string;avatar_url:string|null;approval_status:'pending'|'approved'|'rejected';approval_note:string|null;submitted_at:string|null;years_experience:number;specialties:string[];onboarding_completed:boolean;salon_name:string;address:string;portfolio_count:number;service_count:number};
export function AdminReviewList({initialItems}:{initialItems:Item[]}){
 const [items,setItems]=useState(initialItems);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 async function act(id:string,status:Item['approval_status']){const note=status==='rejected'?(prompt('請輸入補件原因（設計師會收到通知）')||'請補充完整作品、價目與店家資料後再送審。'):'';setBusy(id);setError('');try{const r=await fetch('/api/admin/designers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:id,status,note})});const j=await r.json();if(!r.ok)throw new Error(j.message||'更新失敗');setItems(v=>v.map(x=>x.id===id?{...x,approval_status:status,approval_note:note}:x))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 if(!items.length)return <div className="empty-state"><h3>目前沒有設計師帳號</h3><p className="muted">第一批設計師註冊後會直接出現在這裡。</p></div>;
 return <div>{error&&<div className="form-error">{error}</div>}{items.map(x=><div className="admin-review" key={x.id}><img className="avatar avatar-lg" src={x.avatar_url||'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80'} alt=""/><div className="admin-review-main"><div className="name">{x.display_name} · {x.salon_name}</div><div className="small">{x.email} · {x.address||'未填地址'}</div><div className="tags" style={{marginTop:7}}>{(x.specialties||[]).slice(0,6).map(s=><span className="tag" key={s}>{s}</span>)}<span className="tag">作品 {x.portfolio_count}</span><span className="tag">服務 {x.service_count}</span><span className={`tag ${x.approval_status==='approved'?'approval-ok':x.approval_status==='rejected'?'approval-bad':'approval-wait'}`}>{x.approval_status==='approved'?'已通過':x.approval_status==='rejected'?'需補件':'待審核'}</span></div>{x.approval_note&&<div className="small" style={{marginTop:6}}>備註：{x.approval_note}</div>}</div><div className="admin-review-actions"><button className="btn btn-brand" disabled={busy===x.id} onClick={()=>act(x.id,'approved')}><CheckCircle2 size={15}/>通過</button><button className="btn" disabled={busy===x.id} onClick={()=>act(x.id,'rejected')}><XCircle size={15}/>補件</button>{x.approval_status!=='pending'&&<button className="btn" disabled={busy===x.id} onClick={()=>act(x.id,'pending')}><RotateCcw size={15}/>重審</button>}</div></div>)}</div>
}
