'use client';
import { useState } from 'react';
type Plan={code:string;name:string;monthly_price:number};
type Row={user_id:string|null;display_name:string;email:string;organization_id:string|null;organization_name:string;plan_code:string|null;status:string|null;custom_monthly_price:number|null;discount_percent:number|null;free_until:string|null;comped_forever:boolean|null;admin_note:string|null};
export function AdminBillingTable({rows,plans,subjectType='provider'}:{rows:Row[];plans:Plan[];subjectType?:'provider'|'organization'}){
 const [items,setItems]=useState(rows);const [busy,setBusy]=useState('');const [msg,setMsg]=useState('');
 const key=(x:Row)=>subjectType==='organization'?(x.organization_id||x.user_id||''):(x.user_id||x.organization_id||'');
 async function save(x:Row){const k=key(x);setBusy(k);setMsg('');const r=await fetch('/api/admin/billing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subjectType,userId:x.user_id,organizationId:x.organization_id,planCode:x.plan_code||'pilot',status:x.status||'trial',customMonthlyPrice:x.custom_monthly_price,discountPercent:Number(x.discount_percent||0),freeUntil:x.free_until?x.free_until.slice(0,10):null,compedForever:Boolean(x.comped_forever),adminNote:x.admin_note||''})});const j=await r.json();setBusy('');setMsg(r.ok?'已儲存收費與權限設定':j.message||'儲存失敗')}
 function patch(id:string,k:keyof Row,v:any){setItems(s=>s.map(x=>key(x)===id?{...x,[k]:v}:x))}
 if(!items.length)return <div className="admin-empty">目前沒有符合這個收費類型的帳號。</div>;
 return <>{msg&&<div className="notice-bar">{msg}</div>}<div className="admin-table-wrap"><table className="admin-table admin-billing-table"><thead><tr><th>{subjectType==='organization'?'店家／工作室':'個人服務者'}</th><th>方案</th><th>狀態</th><th>自訂月費</th><th>折扣%</th><th>免費至</th><th>永久免費</th><th>管理</th></tr></thead><tbody>{items.map(x=>{const id=key(x);return <tr key={id}><td><strong>{subjectType==='organization'?x.organization_name:x.display_name}</strong><small>{subjectType==='organization'?`主要聯絡：${x.display_name}${x.email?` · ${x.email}`:''}`:x.email}</small></td><td><select className="input admin-mini-input" value={x.plan_code||'pilot'} onChange={e=>patch(id,'plan_code',e.target.value)}>{plans.map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</select></td><td><select className="input admin-mini-input" value={x.status||'trial'} onChange={e=>patch(id,'status',e.target.value)}><option value="trial">試用</option><option value="active">已付款</option><option value="past_due">待付款</option><option value="paused">暫停</option><option value="cancelled">取消</option></select></td><td><input className="input admin-mini-input" type="number" min="0" placeholder="依方案" value={x.custom_monthly_price??''} onChange={e=>patch(id,'custom_monthly_price',e.target.value===''?null:Number(e.target.value))}/></td><td><input className="input admin-mini-input" type="number" min="0" max="100" value={Number(x.discount_percent||0)} onChange={e=>patch(id,'discount_percent',Number(e.target.value))}/></td><td><input className="input admin-mini-input" type="date" value={x.free_until?x.free_until.slice(0,10):''} onChange={e=>patch(id,'free_until',e.target.value||null)}/></td><td><input type="checkbox" checked={Boolean(x.comped_forever)} onChange={e=>patch(id,'comped_forever',e.target.checked)}/></td><td><button className="btn btn-brand" disabled={!id||busy===id} onClick={()=>save(x)}>{busy===id?'儲存中':'儲存'}</button></td></tr>})}</tbody></table></div></>
}
