import Link from 'next/link';
import { BarChart3, Bell, CalendarDays, Clock3, MessageCircle, PanelsTopLeft, Settings2, Sparkles, ToggleRight, UserRound, UsersRound } from 'lucide-react';
import { BRAND } from '@/lib/brand';
import { demoDemand, providers } from '@/lib/demo-data';

export default function Dashboard(){
  const p=providers[0];
  const leads=[demoDemand,{...demoDemand,id:'d2',serviceLabel:'染髮',budgetMin:2500,budgetMax:4500,location:'竹北市 · 1.6 km',notes:'想做冷棕色，不漂的情況下希望越透越好。',createdAt:'7 分鐘前'},{...demoDemand,id:'d3',serviceLabel:'剪髮',budgetMin:800,budgetMax:1200,location:'竹北市 · 2.1 km',notes:'中長髮想剪層次但不要太碎，希望回家好整理。',createdAt:'18 分鐘前'}];
  const menu=[['工作台',PanelsTopLeft],['需求牆 12',Sparkles],['我的提案',MessageCircle],['預約管理',CalendarDays],['訊息 3',Bell],['顧客管理',UsersRound],['個人檔案',UserRound],['數據分析',BarChart3],['設定',Settings2]] as const;
  return <div className="app-shell"><div className="topbar"><div className="container" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16}}><Link className="brand" href="/"><span className="brand-mark">髮</span>{BRAND.name}｜設計師工作台</Link><div className="provider-row"><span className="status-pill" style={{position:'static'}}>● 接案中</span><img className="avatar" src={p.avatar}/></div></div></div>
    <div className="dashboard"><aside className="sidebar"><div className="brand"><span className="brand-mark">髮</span>{BRAND.name}</div>{menu.map(([x,Icon],i)=><div className={`side-link ${i===0?'active':''}`} key={x}><Icon size={16}/>{x}</div>)}</aside>
      <main className="dashboard-main"><div className="dash-head"><div><div className="eyebrow">DESIGNER CONSOLE</div><h1 className="page-title">下午好，{p.name}</h1><p className="muted">你 3 公里內有 12 筆新需求，最快 5 分鐘前剛發布。</p></div><button className="btn btn-brand"><CalendarDays size={15} style={{verticalAlign:'-3px',marginRight:6}}/>編輯可接時段</button></div>
      <div className="dash-grid"><div className="dash-card"><span className="small">今日新需求</span><strong>12</strong><span className="small" style={{color:'#527d58'}}>↑ 20%</span></div><div className="dash-card"><span className="small">本月提案</span><strong>58</strong><span className="small" style={{color:'#527d58'}}>↑ 14%</span></div><div className="dash-card"><span className="small">成交預約</span><strong>23</strong><span className="small" style={{color:'#527d58'}}>↑ 8%</span></div><div className="dash-card"><span className="small">媒合轉換</span><strong>39.7%</strong><span className="small">本月</span></div></div>
      <div className="layout-2"><section className="panel"><div className="section-head"><div><h3>附近新需求</h3><p className="small">依距離、項目與你的可服務時間排序</p></div><button className="btn">篩選</button></div>{leads.map((d,i)=><div className="lead-row" key={d.id}><img className="avatar" src={['https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80','https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'][i]}/><div><div className="name">{d.serviceLabel} · {d.location}</div><div className="small">預算 NT$ {d.budgetMin} - {d.budgetMax} · {d.createdAt}</div><div style={{marginTop:5}}>{d.notes}</div></div><Link className="btn btn-brand" href={`/pro/request/${d.id}`}>報價</Link></div>)}</section>
      <aside className="panel"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div className="small">目前狀態</div><h3 style={{marginTop:4,color:'#315d3b'}}>營業中</h3></div><ToggleRight size={40} color="#527d58"/></div><div className="summary-row"><span>接受立即需求</span><strong style={{color:'#315d3b'}}>開啟</strong></div><div className="summary-row"><span>接案半徑</span><strong>3 km</strong></div><div className="summary-row"><span>今日可接</span><strong><Clock3 size={13} style={{verticalAlign:'-2px'}}/> 15:30 / 17:00</strong></div><h3 style={{marginTop:24}}>Pro 方案</h3><p className="small" style={{lineHeight:1.75}}>不限提案、即時通知、提高附近曝光、完整數據。收費模組已預留。</p><button className="btn btn-soft" style={{width:'100%'}}>管理訂閱</button></aside></div></main>
    </div></div>
}
